###USERS CREATE (Signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "user_name": "GregHirsch3",
  "password": "password", 
  "password_confirmation": "password" 
}


###SESSIONS CREATE (Login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "user_name": "GregHirsch3",
  "password": "password"
}


###ANXIETIES INDEX
GET http://localhost:3000/anxieties 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyMDY1NjF9.Qaq5snifTAwX6uDXCqAUzIMzzM2bIHMVffrq-zjEm80
Content-Type: application/json


###ANXIETY SHOW
GET http://localhost:3000/anxieties/1.json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyMDY1NjF9.Qaq5snifTAwX6uDXCqAUzIMzzM2bIHMVffrq-zjEm80
Content-Type: application/json



###ANXIETIES CREATE
POST http://localhost:3000/anxieties.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyMDY1NjF9.Qaq5snifTAwX6uDXCqAUzIMzzM2bIHMVffrq-zjEm80
Content-Type: application/json

{
"life_theme": "Girls",
"intrusive_thought_or_feeling": "She loves me, she loves me not",
"obsessional_theme": "Catastrophizing, Mindreading",
"opposite_thought": "I am wonderful no matter what!",
"opposite_action": "Yoga",
"timer": 30
}


###ANXIETIES UPDATE


###ANXIETIES DESTROY



